CREATE DATABASE falcon DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE alarm DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
CREATE DATABASE idx DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
