// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service/service.proto

/*
Package service is a generated protocol buffer package.

It is generated from these files:
	service/service.proto

It has these top-level messages:
	PutRequest
	PutResponse
	GetRequest
	GetResponse
	Empty
	Stats
	StatsName
*/
package service

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import tsdb "github.com/yubo/falcon/lib/tsdb"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Cf int32

const (
	Cf_MIN     Cf = 0
	Cf_MAX     Cf = 1
	Cf_AVERAGE Cf = 2
)

var Cf_name = map[int32]string{
	0: "MIN",
	1: "MAX",
	2: "AVERAGE",
}
var Cf_value = map[string]int32{
	"MIN":     0,
	"MAX":     1,
	"AVERAGE": 2,
}

func (x Cf) String() string {
	return proto.EnumName(Cf_name, int32(x))
}
func (Cf) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ItemType int32

const (
	ItemType_GAUGE   ItemType = 0
	ItemType_DERIVE  ItemType = 1
	ItemType_COUNTER ItemType = 2
)

var ItemType_name = map[int32]string{
	0: "GAUGE",
	1: "DERIVE",
	2: "COUNTER",
}
var ItemType_value = map[string]int32{
	"GAUGE":   0,
	"DERIVE":  1,
	"COUNTER": 2,
}

func (x ItemType) String() string {
	return proto.EnumName(ItemType_name, int32(x))
}
func (ItemType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type PutRequest struct {
	Data []*tsdb.DataPoint `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PutRequest) GetData() []*tsdb.DataPoint {
	if m != nil {
		return m.Data
	}
	return nil
}

type PutResponse struct {
	N int32 `protobuf:"varint,1,opt,name=n" json:"n,omitempty"`
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PutResponse) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type GetRequest struct {
	Keys      []*tsdb.Key `protobuf:"bytes,1,rep,name=keys" json:"keys,omitempty"`
	Start     int64       `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	End       int64       `protobuf:"varint,3,opt,name=end" json:"end,omitempty"`
	ConsolFun Cf          `protobuf:"varint,4,opt,name=consolFun,enum=service.Cf" json:"consolFun,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetRequest) GetKeys() []*tsdb.Key {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *GetRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *GetRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *GetRequest) GetConsolFun() Cf {
	if m != nil {
		return m.ConsolFun
	}
	return Cf_MIN
}

type GetResponse struct {
	Data []*tsdb.DataPoints `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetResponse) GetData() []*tsdb.DataPoints {
	if m != nil {
		return m.Data
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Stats struct {
	Counter []uint64 `protobuf:"varint,1,rep,packed,name=counter" json:"counter,omitempty"`
}

func (m *Stats) Reset()                    { *m = Stats{} }
func (m *Stats) String() string            { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()               {}
func (*Stats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *Stats) GetCounter() []uint64 {
	if m != nil {
		return m.Counter
	}
	return nil
}

type StatsName struct {
	CounterName [][]byte `protobuf:"bytes,1,rep,name=counterName,proto3" json:"counterName,omitempty"`
}

func (m *StatsName) Reset()                    { *m = StatsName{} }
func (m *StatsName) String() string            { return proto.CompactTextString(m) }
func (*StatsName) ProtoMessage()               {}
func (*StatsName) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *StatsName) GetCounterName() [][]byte {
	if m != nil {
		return m.CounterName
	}
	return nil
}

func init() {
	proto.RegisterType((*PutRequest)(nil), "service.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "service.PutResponse")
	proto.RegisterType((*GetRequest)(nil), "service.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "service.GetResponse")
	proto.RegisterType((*Empty)(nil), "service.Empty")
	proto.RegisterType((*Stats)(nil), "service.Stats")
	proto.RegisterType((*StatsName)(nil), "service.StatsName")
	proto.RegisterEnum("service.Cf", Cf_name, Cf_value)
	proto.RegisterEnum("service.ItemType", ItemType_name, ItemType_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Service service

type ServiceClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error)
	GetStatsName(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatsName, error)
}

type serviceClient struct {
	cc *grpc.ClientConn
}

func NewServiceClient(cc *grpc.ClientConn) ServiceClient {
	return &serviceClient{cc}
}

func (c *serviceClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := grpc.Invoke(ctx, "/service.Service/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/service.Service/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := grpc.Invoke(ctx, "/service.Service/GetStats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serviceClient) GetStatsName(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatsName, error) {
	out := new(StatsName)
	err := grpc.Invoke(ctx, "/service.Service/GetStatsName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Service service

type ServiceServer interface {
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetStats(context.Context, *Empty) (*Stats, error)
	GetStatsName(context.Context, *Empty) (*StatsName, error)
}

func RegisterServiceServer(s *grpc.Server, srv ServiceServer) {
	s.RegisterService(&_Service_serviceDesc, srv)
}

func _Service_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Service/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Service/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Service/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Service_GetStatsName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServiceServer).GetStatsName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/service.Service/GetStatsName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServiceServer).GetStatsName(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Service_serviceDesc = grpc.ServiceDesc{
	ServiceName: "service.Service",
	HandlerType: (*ServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _Service_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Service_Get_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _Service_GetStats_Handler,
		},
		{
			MethodName: "GetStatsName",
			Handler:    _Service_GetStatsName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service/service.proto",
}

func init() { proto.RegisterFile("service/service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 501 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x5c, 0x53, 0xdd, 0x8e, 0xd2, 0x40,
	0x18, 0xa5, 0x2d, 0x6c, 0x97, 0xaf, 0xeb, 0xda, 0x0c, 0x6b, 0xd2, 0xe0, 0x4f, 0xea, 0xac, 0x17,
	0xb8, 0x89, 0xad, 0xcb, 0x3e, 0x80, 0x41, 0xb6, 0x36, 0x44, 0x45, 0x32, 0xfb, 0x13, 0xe3, 0x8d,
	0x19, 0x60, 0xc0, 0x46, 0x98, 0xa9, 0xcc, 0x74, 0x93, 0xde, 0x18, 0xe3, 0x2b, 0xf8, 0x68, 0xbe,
	0x82, 0x0f, 0x62, 0x98, 0x16, 0x28, 0x7b, 0xd3, 0xce, 0x39, 0x73, 0xce, 0x69, 0xbf, 0x33, 0x2d,
	0x3c, 0x92, 0x6c, 0x75, 0x97, 0x4c, 0x58, 0x58, 0xde, 0x83, 0x74, 0x25, 0x94, 0x40, 0x76, 0x09,
	0xdb, 0x4f, 0xe6, 0x42, 0xcc, 0x17, 0x2c, 0xa4, 0x69, 0x12, 0x52, 0xce, 0x85, 0xa2, 0x2a, 0x11,
	0x5c, 0x16, 0xb2, 0x76, 0x6b, 0x91, 0x8c, 0x43, 0x25, 0xa7, 0xc5, 0xa5, 0x20, 0xf1, 0x39, 0xc0,
	0x28, 0x53, 0x84, 0xfd, 0xc8, 0x98, 0x54, 0xe8, 0x14, 0xea, 0x53, 0xaa, 0xa8, 0x67, 0xf8, 0x56,
	0xc7, 0xe9, 0x3e, 0x0c, 0xb4, 0xf0, 0x92, 0x2a, 0x3a, 0x12, 0x09, 0x57, 0x44, 0x6f, 0xe2, 0xc7,
	0xe0, 0x68, 0x8b, 0x4c, 0x05, 0x97, 0x0c, 0x1d, 0x81, 0xc1, 0x3d, 0xc3, 0x37, 0x3a, 0x0d, 0x62,
	0x70, 0xfc, 0x13, 0x20, 0x66, 0xdb, 0xbc, 0xa7, 0x50, 0xff, 0xce, 0x72, 0x59, 0xe6, 0x35, 0x8b,
	0xbc, 0xf7, 0x2c, 0x27, 0x9a, 0x46, 0x27, 0xd0, 0x90, 0x8a, 0xae, 0x94, 0x67, 0xfa, 0x46, 0xc7,
	0x22, 0x05, 0x40, 0x2e, 0x58, 0x8c, 0x4f, 0x3d, 0x4b, 0x73, 0xeb, 0x25, 0x7a, 0x09, 0xcd, 0x89,
	0xe0, 0x52, 0x2c, 0xde, 0x65, 0xdc, 0xab, 0xfb, 0x46, 0xe7, 0xb8, 0xeb, 0x04, 0x9b, 0x0e, 0xfa,
	0x33, 0xb2, 0xdb, 0xc5, 0x17, 0xe0, 0xe8, 0xe7, 0x97, 0x2f, 0xf7, 0x62, 0x6f, 0x20, 0xf7, 0xde,
	0x40, 0xb2, 0x9c, 0xc8, 0x86, 0x46, 0xb4, 0x4c, 0x55, 0x8e, 0x9f, 0x43, 0xe3, 0x4a, 0x51, 0x25,
	0x91, 0x07, 0xf6, 0x44, 0x64, 0x5c, 0xb1, 0x95, 0xb6, 0xd6, 0xc9, 0x06, 0xe2, 0x57, 0xd0, 0xd4,
	0x92, 0x21, 0x5d, 0x32, 0xe4, 0x83, 0x53, 0xf2, 0x6b, 0xa8, 0xa5, 0x47, 0xa4, 0x4a, 0x9d, 0x9d,
	0x82, 0xd9, 0x9f, 0x21, 0x1b, 0xac, 0x8f, 0x83, 0xa1, 0x5b, 0xd3, 0x8b, 0xde, 0x67, 0xd7, 0x40,
	0x0e, 0xd8, 0xbd, 0xdb, 0x88, 0xf4, 0xe2, 0xc8, 0x35, 0xcf, 0x02, 0x38, 0x1c, 0x28, 0xb6, 0xbc,
	0xce, 0x53, 0x86, 0x9a, 0xd0, 0x88, 0x7b, 0x37, 0x71, 0xe4, 0xd6, 0x10, 0xc0, 0xc1, 0x65, 0x44,
	0x06, 0xb7, 0x51, 0xa1, 0xef, 0x7f, 0xba, 0x19, 0x5e, 0x47, 0xc4, 0x35, 0xbb, 0xbf, 0x4c, 0xb0,
	0xaf, 0x8a, 0xf1, 0x51, 0x17, 0xac, 0x51, 0xa6, 0x50, 0x6b, 0xdb, 0xc7, 0xee, 0x38, 0xdb, 0x27,
	0xfb, 0x64, 0xd1, 0x09, 0xae, 0xad, 0x3d, 0x31, 0xab, 0x7a, 0x76, 0x47, 0x56, 0xf1, 0x54, 0x7a,
	0xc4, 0x35, 0xf4, 0x06, 0x0e, 0x63, 0xa6, 0x8a, 0x76, 0x8e, 0xb7, 0x1a, 0x5d, 0x5b, 0x7b, 0x87,
	0xf5, 0x3e, 0x6e, 0xfd, 0xfe, 0xfb, 0xef, 0x8f, 0xf9, 0x00, 0x39, 0xe1, 0xdd, 0x79, 0xf0, 0x3a,
	0x94, 0xda, 0xf4, 0x01, 0x8e, 0x36, 0x01, 0xba, 0xbb, 0xfb, 0x21, 0x68, 0x3f, 0x64, 0xad, 0xc1,
	0x9e, 0x0e, 0x42, 0xc8, 0xad, 0x04, 0x7d, 0xe5, 0x74, 0xc9, 0xde, 0xfa, 0x5f, 0x9e, 0xcd, 0x13,
	0xf5, 0x2d, 0x1b, 0x07, 0x13, 0xb1, 0x0c, 0xf3, 0x6c, 0x2c, 0xc2, 0x19, 0x5d, 0x4c, 0x04, 0xdf,
	0xfc, 0x1b, 0xe3, 0x03, 0xfd, 0x81, 0x5f, 0xfc, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x26, 0x5d, 0x05,
	0x70, 0x35, 0x03, 0x00, 0x00,
}
