// Code generated by protoc-gen-go. DO NOT EDIT.
// source: modules/transfer/transfer.proto

/*
Package transfer is a generated protocol buffer package.

It is generated from these files:
	modules/transfer/transfer.proto

It has these top-level messages:
	DataPoint
	DataPoints
	PutRequest
	PutResponse
	GetRequest
	GetResponse
	Empty
	Stats
	StatsName
*/
package transfer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import tsdb "github.com/yubo/falcon/lib/tsdb"
import service "github.com/yubo/falcon/modules/service"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DataPoint struct {
	Key   []byte              `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value *tsdb.TimeValuePair `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
}

func (m *DataPoint) Reset()                    { *m = DataPoint{} }
func (m *DataPoint) String() string            { return proto.CompactTextString(m) }
func (*DataPoint) ProtoMessage()               {}
func (*DataPoint) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DataPoint) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DataPoint) GetValue() *tsdb.TimeValuePair {
	if m != nil {
		return m.Value
	}
	return nil
}

type DataPoints struct {
	Key    []byte                `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Values []*tsdb.TimeValuePair `protobuf:"bytes,2,rep,name=values" json:"values,omitempty"`
}

func (m *DataPoints) Reset()                    { *m = DataPoints{} }
func (m *DataPoints) String() string            { return proto.CompactTextString(m) }
func (*DataPoints) ProtoMessage()               {}
func (*DataPoints) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DataPoints) GetKey() []byte {
	if m != nil {
		return m.Key
	}
	return nil
}

func (m *DataPoints) GetValues() []*tsdb.TimeValuePair {
	if m != nil {
		return m.Values
	}
	return nil
}

type PutRequest struct {
	Data []*DataPoint `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *PutRequest) Reset()                    { *m = PutRequest{} }
func (m *PutRequest) String() string            { return proto.CompactTextString(m) }
func (*PutRequest) ProtoMessage()               {}
func (*PutRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PutRequest) GetData() []*DataPoint {
	if m != nil {
		return m.Data
	}
	return nil
}

type PutResponse struct {
	N int32 `protobuf:"varint,1,opt,name=n" json:"n,omitempty"`
}

func (m *PutResponse) Reset()                    { *m = PutResponse{} }
func (m *PutResponse) String() string            { return proto.CompactTextString(m) }
func (*PutResponse) ProtoMessage()               {}
func (*PutResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PutResponse) GetN() int32 {
	if m != nil {
		return m.N
	}
	return 0
}

type GetRequest struct {
	Keys      [][]byte   `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	Start     int64      `protobuf:"varint,2,opt,name=start" json:"start,omitempty"`
	End       int64      `protobuf:"varint,3,opt,name=end" json:"end,omitempty"`
	ConsolFun service.Cf `protobuf:"varint,4,opt,name=consolFun,enum=service.Cf" json:"consolFun,omitempty"`
}

func (m *GetRequest) Reset()                    { *m = GetRequest{} }
func (m *GetRequest) String() string            { return proto.CompactTextString(m) }
func (*GetRequest) ProtoMessage()               {}
func (*GetRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetRequest) GetKeys() [][]byte {
	if m != nil {
		return m.Keys
	}
	return nil
}

func (m *GetRequest) GetStart() int64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *GetRequest) GetEnd() int64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *GetRequest) GetConsolFun() service.Cf {
	if m != nil {
		return m.ConsolFun
	}
	return service.Cf_MIN
}

type GetResponse struct {
	Data []*DataPoints `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *GetResponse) Reset()                    { *m = GetResponse{} }
func (m *GetResponse) String() string            { return proto.CompactTextString(m) }
func (*GetResponse) ProtoMessage()               {}
func (*GetResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *GetResponse) GetData() []*DataPoints {
	if m != nil {
		return m.Data
	}
	return nil
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type Stats struct {
	Counter []uint64 `protobuf:"varint,1,rep,packed,name=counter" json:"counter,omitempty"`
}

func (m *Stats) Reset()                    { *m = Stats{} }
func (m *Stats) String() string            { return proto.CompactTextString(m) }
func (*Stats) ProtoMessage()               {}
func (*Stats) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *Stats) GetCounter() []uint64 {
	if m != nil {
		return m.Counter
	}
	return nil
}

type StatsName struct {
	CounterName [][]byte `protobuf:"bytes,1,rep,name=counterName,proto3" json:"counterName,omitempty"`
}

func (m *StatsName) Reset()                    { *m = StatsName{} }
func (m *StatsName) String() string            { return proto.CompactTextString(m) }
func (*StatsName) ProtoMessage()               {}
func (*StatsName) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *StatsName) GetCounterName() [][]byte {
	if m != nil {
		return m.CounterName
	}
	return nil
}

func init() {
	proto.RegisterType((*DataPoint)(nil), "transfer.DataPoint")
	proto.RegisterType((*DataPoints)(nil), "transfer.DataPoints")
	proto.RegisterType((*PutRequest)(nil), "transfer.PutRequest")
	proto.RegisterType((*PutResponse)(nil), "transfer.PutResponse")
	proto.RegisterType((*GetRequest)(nil), "transfer.GetRequest")
	proto.RegisterType((*GetResponse)(nil), "transfer.GetResponse")
	proto.RegisterType((*Empty)(nil), "transfer.Empty")
	proto.RegisterType((*Stats)(nil), "transfer.Stats")
	proto.RegisterType((*StatsName)(nil), "transfer.StatsName")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for Transfer service

type TransferClient interface {
	Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error)
	GetStatsName(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatsName, error)
}

type transferClient struct {
	cc *grpc.ClientConn
}

func NewTransferClient(cc *grpc.ClientConn) TransferClient {
	return &transferClient{cc}
}

func (c *transferClient) Put(ctx context.Context, in *PutRequest, opts ...grpc.CallOption) (*PutResponse, error) {
	out := new(PutResponse)
	err := grpc.Invoke(ctx, "/transfer.Transfer/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	out := new(GetResponse)
	err := grpc.Invoke(ctx, "/transfer.Transfer/Get", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferClient) GetStats(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Stats, error) {
	out := new(Stats)
	err := grpc.Invoke(ctx, "/transfer.Transfer/GetStats", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *transferClient) GetStatsName(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatsName, error) {
	out := new(StatsName)
	err := grpc.Invoke(ctx, "/transfer.Transfer/GetStatsName", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for Transfer service

type TransferServer interface {
	Put(context.Context, *PutRequest) (*PutResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetStats(context.Context, *Empty) (*Stats, error)
	GetStatsName(context.Context, *Empty) (*StatsName, error)
}

func RegisterTransferServer(s *grpc.Server, srv TransferServer) {
	s.RegisterService(&_Transfer_serviceDesc, srv)
}

func _Transfer_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transfer.Transfer/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServer).Put(ctx, req.(*PutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transfer_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transfer.Transfer/Get",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transfer_GetStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServer).GetStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transfer.Transfer/GetStats",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServer).GetStats(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Transfer_GetStatsName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TransferServer).GetStatsName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/transfer.Transfer/GetStatsName",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TransferServer).GetStatsName(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

var _Transfer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "transfer.Transfer",
	HandlerType: (*TransferServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _Transfer_Put_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _Transfer_Get_Handler,
		},
		{
			MethodName: "GetStats",
			Handler:    _Transfer_GetStats_Handler,
		},
		{
			MethodName: "GetStatsName",
			Handler:    _Transfer_GetStatsName_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "modules/transfer/transfer.proto",
}

func init() { proto.RegisterFile("modules/transfer/transfer.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 517 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x93, 0xdf, 0x8e, 0xd2, 0x40,
	0x14, 0xc6, 0x53, 0xfe, 0xec, 0xc2, 0x29, 0xae, 0x9b, 0x01, 0x93, 0x06, 0x35, 0xe2, 0xdc, 0x2c,
	0x68, 0xa4, 0x8a, 0x31, 0x26, 0xde, 0xf9, 0x97, 0x4d, 0x4c, 0x36, 0xa4, 0x6e, 0xbc, 0xf0, 0xc6,
	0x0c, 0x30, 0x60, 0xb3, 0xed, 0x4c, 0xed, 0x9c, 0x21, 0xe1, 0xd6, 0x57, 0xf0, 0x49, 0x7c, 0x16,
	0x5f, 0xc1, 0x07, 0x31, 0x3d, 0x6d, 0xa1, 0x8b, 0xeb, 0x0d, 0x9c, 0x73, 0xfa, 0x9d, 0xdf, 0xcc,
	0xf7, 0x25, 0x03, 0x0f, 0x62, 0xbd, 0xb4, 0x91, 0x34, 0x3e, 0xa6, 0x42, 0x99, 0x95, 0x4c, 0x77,
	0xc5, 0x38, 0x49, 0x35, 0x6a, 0xd6, 0x2a, 0xfb, 0xfe, 0xbd, 0xb5, 0xd6, 0xeb, 0x48, 0xfa, 0x22,
	0x09, 0x7d, 0xa1, 0x94, 0x46, 0x81, 0xa1, 0x56, 0x26, 0xd7, 0xf5, 0xbb, 0x51, 0x38, 0xf7, 0xd1,
	0x2c, 0xf3, 0x9f, 0x62, 0x78, 0xbf, 0xa4, 0x1b, 0x99, 0x6e, 0xc2, 0x85, 0x2c, 0xff, 0xf3, 0xcf,
	0xfc, 0x1c, 0xda, 0xef, 0x04, 0x8a, 0x99, 0x0e, 0x15, 0xb2, 0x53, 0xa8, 0x5f, 0xc9, 0xad, 0xe7,
	0x0c, 0x9c, 0x61, 0x27, 0xc8, 0x4a, 0x36, 0x82, 0xe6, 0x46, 0x44, 0x56, 0x7a, 0xb5, 0x81, 0x33,
	0x74, 0x27, 0xdd, 0x31, 0x91, 0x2f, 0xc3, 0x58, 0x7e, 0xce, 0xc6, 0x33, 0x11, 0xa6, 0x41, 0xae,
	0xe0, 0x1f, 0x01, 0x76, 0x24, 0x73, 0x03, 0xea, 0x31, 0x1c, 0x91, 0xd0, 0x78, 0xb5, 0x41, 0xfd,
	0x7f, 0xac, 0x42, 0xc2, 0x5f, 0x00, 0xcc, 0x2c, 0x06, 0xf2, 0xbb, 0x95, 0x06, 0xd9, 0x19, 0x34,
	0x96, 0x02, 0x85, 0xe7, 0x94, 0x8b, 0x65, 0x3e, 0xbb, 0x03, 0x03, 0x12, 0xf0, 0xbb, 0xe0, 0xd2,
	0x9a, 0x49, 0xb4, 0x32, 0x92, 0x75, 0xc0, 0x51, 0x74, 0x85, 0x66, 0xe0, 0x28, 0x6e, 0x00, 0xa6,
	0x72, 0xc7, 0x64, 0xd0, 0xb8, 0x92, 0x5b, 0x43, 0xcc, 0x4e, 0x40, 0x35, 0xeb, 0x41, 0xd3, 0xa0,
	0x48, 0x91, 0xdc, 0xd6, 0x83, 0xbc, 0xc9, 0xac, 0x48, 0xb5, 0xf4, 0xea, 0x34, 0xcb, 0x4a, 0x36,
	0x82, 0xf6, 0x42, 0x2b, 0xa3, 0xa3, 0x0f, 0x56, 0x79, 0x8d, 0x81, 0x33, 0x3c, 0x99, 0xb8, 0xe3,
	0x32, 0xd7, 0xb7, 0xab, 0x60, 0xff, 0x95, 0xbf, 0x04, 0x97, 0x0e, 0x2d, 0x6e, 0x34, 0xbc, 0xe6,
	0xa4, 0x77, 0x83, 0x13, 0x53, 0x58, 0x39, 0x86, 0xe6, 0xfb, 0x38, 0xc1, 0x2d, 0x7f, 0x08, 0xcd,
	0x4f, 0x28, 0xd0, 0x30, 0x0f, 0x8e, 0x17, 0xda, 0x2a, 0x94, 0x29, 0xad, 0x37, 0x82, 0xb2, 0xe5,
	0x4f, 0xa0, 0x4d, 0x92, 0x0b, 0x11, 0x4b, 0x36, 0x00, 0xb7, 0x98, 0x67, 0x6d, 0xe1, 0xaf, 0x3a,
	0x9a, 0xfc, 0xaa, 0x41, 0xeb, 0xb2, 0x38, 0x98, 0x9d, 0x43, 0x7d, 0x66, 0x91, 0x55, 0xae, 0xb2,
	0x0f, 0xbe, 0x7f, 0xe7, 0x60, 0x9a, 0xbb, 0xe0, 0xbd, 0x1f, 0xbf, 0xff, 0xfc, 0xac, 0x9d, 0xf0,
	0xb6, 0xbf, 0x79, 0x36, 0x7e, 0xea, 0x27, 0x16, 0x5f, 0x39, 0x8f, 0x32, 0xd2, 0x54, 0x5e, 0x23,
	0xed, 0xe3, 0xae, 0x92, 0x2a, 0x79, 0x1c, 0x92, 0xd6, 0x92, 0x48, 0xaf, 0xa1, 0x35, 0x95, 0x98,
	0xbb, 0xbe, 0xbd, 0x5f, 0xa4, 0x3c, 0xfa, 0x95, 0x01, 0x29, 0x78, 0x97, 0x18, 0xb7, 0x98, 0x9b,
	0x33, 0x0c, 0xad, 0x5d, 0x40, 0xa7, 0x44, 0x50, 0x2a, 0xff, 0x60, 0xba, 0x07, 0x98, 0x4c, 0xc5,
	0x3d, 0x42, 0x31, 0x76, 0x5a, 0x41, 0x7d, 0x55, 0x22, 0x96, 0x6f, 0x46, 0x5f, 0xce, 0xd6, 0x21,
	0x7e, 0xb3, 0xf3, 0xf1, 0x42, 0xc7, 0xfe, 0xd6, 0xce, 0xb5, 0xbf, 0x12, 0xd1, 0x42, 0x2b, 0xff,
	0xf0, 0xf5, 0xce, 0x8f, 0xe8, 0x65, 0x3d, 0xff, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x76, 0xbc,
	0x51, 0xd8, 0x03, 0x00, 0x00,
}
