/*
 * Copyright 2016,2017 falcon Author. All rights reserved.
 * Use of this source code is governed by a BSD-style
 * license that can be found in the LICENSE file.
 */
package core

import "errors"

var (
	ErrLogged         = errors.New("already logged in")
	ErrInUse          = errors.New("object in use")
	ErrExist          = errors.New("object exists")
	ErrNoExits        = errors.New("object not exists")
	ErrNoModule       = errors.New("module not exists")
	ErrNoLogged       = errors.New("not logged in")
	ErrLogin          = errors.New("login failed")
	ErrRePreStart     = errors.New("multiple times PreStart")
	ErrUnsupported    = errors.New("unsupported")
	ErrDelDefault     = errors.New("You cannot delete this basic data")
	ENONODE           = errors.New("no such node")
	ErrDelInUse       = errors.New("Still in use, cannot remove")
	ErrParam          = errors.New("param error")
	ErrEmpty          = errors.New("empty items")
	ErrNoEmpty        = errors.New("not empty items")
	EPERM             = errors.New("Operation not permitted")
	ENOENT            = errors.New("No such file or directory")
	ESRCH             = errors.New("No such process")
	EINTR             = errors.New("Interrupted system call")
	EIO               = errors.New("I/O error")
	ENXIO             = errors.New("No such device or address")
	E2BIG             = errors.New("Argument list too long")
	ENOEXEC           = errors.New("Exec format error")
	EBADF             = errors.New("Bad file number")
	ECHILD            = errors.New("No child processes")
	EAGAIN            = errors.New("Try again")
	ENOMEM            = errors.New("Out of memory")
	EACCES            = errors.New("Permission denied")
	EFAULT            = errors.New("Bad address")
	ENOTBLK           = errors.New("Block device required")
	EBUSY             = errors.New("Device or resource busy")
	EEXIST            = errors.New("File exists")
	EXDEV             = errors.New("Cross-device link")
	ENODEV            = errors.New("No such device")
	ENOTDIR           = errors.New("Not a directory")
	EISDIR            = errors.New("Is a directory")
	EINVAL            = errors.New("Invalid argument")
	ENFILE            = errors.New("File table overflow")
	EMFILE            = errors.New("Too many open files")
	ENOTTY            = errors.New("Not a typewriter")
	ETXTBSY           = errors.New("Text file busy")
	EFBIG             = errors.New("File too large")
	ENOSPC            = errors.New("No space left on device")
	ESPIPE            = errors.New("Illegal seek")
	EROFS             = errors.New("Read-only file system")
	EMLINK            = errors.New("Too many links")
	EPIPE             = errors.New("Broken pipe")
	EDOM              = errors.New("Math argument out of domain of func")
	ERANGE            = errors.New("Math result not representable")
	EFMT              = errors.New("Invalid format") // custom
	EALLOC            = errors.New("Allocation Failure")
	ErrBalancerClosed = errors.New("grpc: balancer is closed")
	EREACH            = errors.New("Destination address is unreachable")
)
